flake: fix two versions of python in shell
Fixes:
```
Traceback (most recent call last):
  File "/home/jakubgs/work/infra-eth2/ansible/lookup_plugins/vault.py", line 6, in <module>
    import hvac
ModuleNotFoundError: No module named 'hvac'
```
Before.
```
 > echo $PATH | tr ':' '\n' | grep python3-
/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin
/nix/store/38nsff4vmhjmvfsi864yb23y9rk9gw5c-python3-3.11.9-env/bin
```
After the fix.
```
 > echo $PATH | tr ':' '\n' | grep python3-
/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin
/nix/store/pxgdzih20d368bx0h0kzyln5hl5cjgyl-python3-3.12.4-env/bin
```
Caused by upgrade to `unstable` without checking default Python version.

Signed-off-by: Jakub Sokołowski <jakub@status.im>